import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../js/game/Game.js';
import {freshSave,SaveSystem} from '../js/systems/SaveSystem.js';
import {AssetManager} from '../js/systems/AssetManager.js';
import {spawnEnemy} from '../js/systems/EnemySystem.js';
import {updateWeapons,fire} from '../js/systems/WeaponSystem.js';
import {primaryVolley,sixSevenDamage} from '../js/systems/SixSeven.js';
import {endlessPressure} from '../js/systems/ModeSystem.js';
const setup=()=>{const g=new Game(freshSave(),{rng:()=>.5});g.start('tung');g.state='PLAYING';g.player.passive=Infinity;g.spawnTimer=Infinity;g.chestTimer=Infinity;return g;};
const victory=g=>{g.wave=15;const b=spawnEnemy(g,'absolute',true);g.damageEnemy(b,1e9);return g;};
const tick=(g,n)=>{for(let i=0;i<n;i++)g.update(1/60);};
const memory=()=>({value:null,getItem(){return this.value;},setItem(k,v){this.value=v;}});
test('missing, invalid-size and hanging images fall back without rejecting preload',async()=>{
 for(const factory of [()=>{throw Error('missing');},()=>({set src(v){this.onerror();}}),()=>({set src(v){this.naturalWidth=1;this.naturalHeight=1;this.onload();}}),()=>({set src(v){}})]){
  const a=new AssetManager({imageFactory:factory,timeout:2});await a.preload();assert.equal(a.ready,true);assert.equal(a.failed.size,4);assert.equal(a.draw(null,'tung'),false);
 }
});
test('valid images preload once and have no hanging handlers',async()=>{let count=0;const a=new AssetManager({imageFactory:()=>{count++;return {naturalWidth:1024,naturalHeight:128,set src(v){this.onload();}};}});await a.preload();await a.preload();assert.equal(count,4);assert.equal(a.images.get('tung').onerror,null);});
test('67 fires on 67 and 134, never 66 or 68',()=>{const g=setup();g.player.upgrades.sixSeven=1;for(let i=1;i<=134;i++){primaryVolley(g,10,0);assert.equal(g.projectiles.filter(q=>q.sixSeven).length,Math.floor(i/67));}assert.equal(g.player.sixSevenCounter,0);assert.equal(g.projectiles[0].damage,67);});
test('primary multishot and evolution increment once; other weapons and passives do not count',()=>{const g=setup();g.player.upgrades.sixSeven=1;g.player.b.count=5;g.player.b.double=1;g.player.weapons=[{id:'basic',level:8,evolved:true,timer:0},{id:'toxic',level:8,timer:0},{id:'burp',level:1,timer:0}];const e=spawnEnemy(g,'tank');e.x=400;e.y=0;e.hp=1e8;g.grid.rebuild(g.enemies);updateWeapons(g,.001);assert.equal(g.player.primaryAttacks,1);assert.equal(g.player.sixSevenCounter,1);assert.ok(g.projectiles.length>6);});
test('damage multipliers, pierce and absolute chance apply at all five levels',()=>{for(let level=1;level<=5;level++){const g=setup();g.player.upgrades.sixSeven=level;g.player.sixSevenCounter=66;g.player.b.pierce=2;primaryVolley(g,15,0);const q=g.projectiles[0];assert.equal(q.damage,15*sixSevenDamage(level));assert.equal(q.pierce,level+3);assert.equal(q.absolute,false);}const g=setup();g.rng=()=>.01;g.player.upgrades.sixSeven=5;g.player.sixSevenCounter=66;primaryVolley(g,10,0);assert.equal(g.projectiles[0].absolute,true);assert.equal(g.projectiles[0].damage,334);});
test('67 hits enemies with scaled damage once and expires; swept collision catches fast shots',()=>{const g=setup();g.player.weapons=[];g.player.b={damage:.5};g.player.upgrades.sixSeven=1;g.player.sixSevenCounter=66;const e=spawnEnemy(g,'tank');e.x=55;e.y=0;e.hp=1000;g.grid.rebuild(g.enemies);primaryVolley(g,10,0);updateWeapons(g,.25);assert.equal(e.hp,899.5);for(let i=0;i<260;i++)updateWeapons(g,1/60);assert.equal(g.projectiles.length,0);});
test('first impact produces only six shards and seven bounded delayed explosions at level 4',()=>{const g=setup();g.player.weapons=[];g.player.upgrades.sixSeven=4;g.player.sixSevenCounter=66;const e=spawnEnemy(g,'tank');e.x=70;e.y=0;e.hp=1e8;g.grid.rebuild(g.enemies);primaryVolley(g,10,0);updateWeapons(g,.1);assert.equal(g.projectiles.filter(q=>!q.sixSeven).length,6);assert.equal(g.delayedImpacts.length,7);tick(g,60);assert.equal(g.delayedImpacts.length,0);});
test('earned 67 is not dropped at the projectile cap',()=>{const g=setup();g.player.upgrades.sixSeven=1;g.player.sixSevenCounter=66;for(let i=0;i<650;i++)fire(g,0,0,0);primaryVolley(g,10,0);assert.equal(g.projectiles.length,650);assert.equal(g.projectiles.filter(q=>q.sixSeven).length,1);});
test('unlock starts a fresh 67 count rather than inheriting prior volleys',()=>{const g=setup();for(let i=0;i<66;i++)primaryVolley(g,10,0);g.player.upgrades.sixSeven=1;primaryVolley(g,10,0);assert.equal(g.player.sixSevenCounter,1);assert.equal(g.projectiles.length,0);});
test('Wave 15 victory freezes threats and records victory immediately exactly once',()=>{const g=setup();g.enemyBullets.push({});g.zones.push({hostile:true});g.pendingLevels=2;victory(g);assert.equal(g.state,'POST_VICTORY');assert.equal(g.active(),false);assert.equal(g.save.stats.victories,1);assert.equal(g.save.stats.runs,0);assert.equal(g.save.dna,0);assert.equal(g.enemyBullets.length,0);assert.equal(g.enemies.length,0);assert.equal(g.zones.length,0);const time=g.time;tick(g,60);g.pause();g.postVictory();assert.equal(g.time,time);assert.equal(g.state,'POST_VICTORY');assert.equal(g.save.stats.victories,1);});
test('Finish Run settles earned victory once',()=>{const g=victory(setup());g.finish(true);const dna=g.save.dna;g.finish(true);g.finish(false);assert.equal(g.result.victory,true);assert.equal(g.state,'RESULTS');assert.equal(g.save.stats.victories,1);assert.equal(g.save.stats.runs,1);assert.equal(g.save.dna,dna);assert.equal(g.enterEndless(),false);});
test('Endless retains character, current HP, level, build, buffs, stats, pending choices',()=>{const g=setup();g.player.weapons[0].evolved=true;g.player.upgrades.sixSeven=3;g.player.level=30;g.buffs.sigma=7;g.pendingLevels=2;victory(g);const p=g.player;const hp=p.hp,kills=g.kills;assert.equal(g.enterEndless(),true);assert.equal(g.state,'LEVEL_UP');g.choose(0);g.choose(0);assert.equal(g.state,'ENDLESS');assert.equal(g.player,p);assert.ok(g.player.hp>=hp);assert.equal(g.player.weapons[0].evolved,true);assert.equal(g.player.upgrades.sixSeven,3);assert.equal(g.buffs.sigma,7);assert.equal(g.kills,kills);});
test('Endless pressure grows across multiple dimensions; timer pauses correctly',()=>{const g=victory(setup());g.enterEndless();tick(g,60);assert.ok(g.endlessTime>.99);g.pause();tick(g,60);assert.ok(g.endlessTime<1.01);g.resume();assert.equal(g.state,'ENDLESS');const a=endlessPressure(0),b=endlessPressure(600);for(const key of ['hp','damage','cap','elite','speed','shooters'])assert.ok(b[key]>a[key],key);assert.ok(b.interval<a.interval);});
test('Endless schedules bosses once per interval and caps simultaneous bosses',()=>{const g=victory(setup());g.enterEndless();g.endlessTime=119.99;g.update(.02);assert.equal(g.enemies.filter(e=>e.boss).length,1);g.update(.02);assert.equal(g.enemies.filter(e=>e.boss).length,1);g.endlessTime=239.99;g.update(.02);assert.equal(g.enemies.filter(e=>e.boss).length,2);g.endlessTime=359.99;g.update(.02);assert.equal(g.enemies.filter(e=>e.boss).length,2);});
test('Endless absolute boss never reopens victory and increments boss stats',()=>{const g=victory(setup());g.enterEndless();const b=spawnEnemy(g,'absolute',true);g.damageEnemy(b,1e9);assert.equal(g.state,'ENDLESS');assert.equal(g.endlessBosses,1);assert.equal(g.save.stats.endlessBossesKilled,1);assert.equal(g.save.stats.victories,1);});
test('Endless death preserves victory, gives additional DNA once and persists record',()=>{const g=victory(setup());g.enterEndless();g.endlessTime=517;g.endlessBosses=3;g.hurt(1e9);assert.equal(g.state,'RESULTS');assert.equal(g.result.victory,true);assert.equal(g.result.endlessTime,517);assert.equal(g.result.endlessBonus,24+15+16);assert.equal(g.save.stats.bestEndlessTime,517);const dna=g.save.dna;g.finish(false);assert.equal(g.save.dna,dna);assert.equal(g.save.stats.victories,1);});
test('old saves keep currency, purchases and settings and migrate mode defaults',()=>{const raw={version:1,dna:120,upgrades:{health1:1},characters:{chaos:true},stats:{victories:1,kills:750},settings:{lang:'en'}};const mem=memory();mem.value=JSON.stringify(raw);const store=new SaveSystem(mem);assert.equal(store.data.dna,120);assert.equal(store.data.upgrades.health1,1);assert.equal(store.data.settings.lang,'en');assert.equal(store.data.stats.kills,750);assert.equal(store.data.stats.bestEndlessTime,0);assert.equal(store.data.modes.superVomitUnlocked,true);store.write();assert.equal(new SaveSystem(mem).data.modes.superVomitUnlocked,true);});
test('victory reload cannot repeat rewards; new saves keep boss rush locked',()=>{const mem=memory();const store=new SaveSystem(mem);const g=new Game(store.data,{onEvent:t=>{if(t==='save')store.write();}});assert.equal(g.start('tung','SUPER_VOMIT'),false);g.start('tung');g.state='PLAYING';victory(g);const reload=new SaveSystem(mem);assert.equal(reload.data.stats.victories,1);assert.equal(reload.data.dna,0);assert.equal(reload.data.modes.superVomitUnlocked,true);const other=new Game(reload.data);assert.equal(other.state,'MENU');});
test('Super Vomit has five preparation choices and real accelerated build',()=>{const g=setup();g.save.modes.superVomitUnlocked=true;assert.ok(g.start('cup','SUPER_VOMIT'));assert.equal(g.player.level,11);assert.equal(g.player.weapons[0].level,6);assert.equal(g.state,'LEVEL_UP');assert.equal(g.enemies.length,0);for(let i=0;i<5;i++){assert.equal(g.options.length,3);assert.ok(g.choose(0));}assert.equal(g.state,'SUPER_VOMIT_PREP');tick(g,151);assert.equal(g.state,'SUPER_VOMIT_PLAYING');assert.equal(g.enemies.filter(e=>e.boss).length,1);assert.equal(g.superRound,1);});
test('boss rush rounds advance after all bosses die, recover, upgrade and persist best round',()=>{const g=setup();g.save.modes.superVomitUnlocked=true;g.start('tung','SUPER_VOMIT');for(let i=0;i<5;i++)g.choose(0);tick(g,151);const b=g.boss;g.damageEnemy(b,1e9);assert.equal(g.state,'LEVEL_UP');assert.equal(g.save.stats.highestSuperVomitBoss,1);g.choose(0);g.choose(0);tick(g,151);assert.equal(g.superRound,2);assert.equal(g.boss.type,'weird');assert.equal(g.save.stats.victories,0);g.finish(false);assert.equal(g.result.superDefeated,1);});
test('double boss rush waits for both bosses and does not register normal victories',()=>{const g=setup();g.mode='SUPER_VOMIT';g.state='SUPER_VOMIT_PLAYING';g.superRound=8;const a=spawnEnemy(g,'absolute',true),b=spawnEnemy(g,'breaker',true);g.damageEnemy(a,1e9);assert.equal(g.state,'SUPER_VOMIT_PLAYING');g.damageEnemy(b,1e9);assert.equal(g.state,'LEVEL_UP');assert.equal(g.save.stats.highestSuperVomitBoss,8);assert.equal(g.save.stats.victories,0);});

test('asset metadata matches runtime anchors and atlas files exist',async()=>{const {readFile,stat}=await import('node:fs/promises');const {characterAssets}=await import('../js/systems/AssetManager.js');for(const [id,meta]of Object.entries(characterAssets)){const cfg=JSON.parse(await readFile(new URL(`../assets/characters/${id}.json`,import.meta.url)));assert.equal(cfg.anchorY,meta.anchorY);assert.equal(cfg.frameSize,128);assert.equal(cfg.directions.length,8);assert.ok((await stat(new URL(`../assets/characters/${id}.webp`,import.meta.url))).size>1000);}});
test('distant boss rush bosses catch up without accelerating close-range telegraphs',async()=>{const {updateEnemies}=await import('../js/systems/EnemySystem.js');const g=setup();g.mode='SUPER_VOMIT';g.superRound=1;const b=spawnEnemy(g,'clubber',true);b.x=1200;b.y=0;const before=b.x;updateEnemies(g,.1);assert.ok(before-b.x>g.player.character.speed*.1);b.x=200;b.attackTimer=0;updateEnemies(g,.01);assert.ok(b.warning.time>=1);});
test('particles, lightning, zones and abandoned chests stay bounded in extended runs',()=>{const g=setup();g.chests=Array.from({length:100},(_,i)=>({x:999+i,y:999,r:22}));g.effects=Array.from({length:300},()=>({life:2,total:2}));g.particle(0,0,'#fff',999);tick(g,1);assert.ok(g.chests.length<=24);assert.ok(g.effects.length<=100);assert.ok(g.particles.length<=300);});
test('late boss rush adds bounded support and readable delayed hazards',()=>{const g=setup();g.mode='SUPER_VOMIT';g.state='SUPER_VOMIT_PLAYING';g.superRound=20;g.supportTimer=0;g.modeHazardTimer=0;g.update(.01);assert.equal(g.enemies.filter(e=>!e.boss).length,1);assert.equal(g.zones.filter(z=>z.hostile).length,3);assert.ok(g.zones.every(z=>z.life>1.3));});
test('Endless scales actual boss pattern damage, not only contact damage',async()=>{const {updateEnemies}=await import('../js/systems/EnemySystem.js');const g=victory(setup());g.enterEndless();g.endlessTime=600;const b=spawnEnemy(g,'weird',true);b.x=300;b.y=0;b.warning={kind:'burst',time:0,total:1};updateEnemies(g,.01);assert.ok(g.enemyBullets.length>0);assert.ok(g.enemyBullets[0].damage>15);});
