import {poolFor,rewardDefinitions,spinCasino,settleCasino,skipCasino,rewardOutcome,sectorsFor,finalRotation,sectorAtRotation} from '../systems/CasinoSystem.js';
export function casinoLabel(ui,id){return ui.l(rewardDefinitions[id]||[id,id]);}
export function renderCasino(ui){const c=ui.g.save.casino;if(!c){ui.show('MENU');return;}const pool=poolFor(c),pending=c.status==='pending',ready=c.status==='ready',done=!pending&&!ready;
 ui.root.innerHTML=`<section class="dialog casino"><span class="eyebrow">${c.victory?'WAVE 15 · VICTORY WHEEL':'ONE RUN · ONE FREE SPIN'}</span><h1>${c.victory?'VICTORY<br>WHEEL':'BRAINROT<br>CASINO'}</h1><p>${ui.store.available?ui.tr('ДНК за забег уже сохранена','Run DNA is already saved'):ui.tr('ДНК начислена на эту сессию','Run DNA credited for this session')}: <b>+${c.baseDNA}</b> 🧬</p><div class="wheel-wrap"><div class="wheel-pointer">▼</div><canvas id="casino-wheel" width="600" height="600" role="img" aria-label="${ui.tr('Колесо бонусов','Bonus wheel')}"></canvas><div class="wheel-hub">${c.victory?'★':'BR'}</div></div><div class="jackpot-odds">★ JACKPOT · ${Math.round(sectorsFor(c).find(s=>s.id==='triple').angle/(2*Math.PI)*100)}%</div><div id="casino-outcome" role="status" aria-live="polite">${pending?`<h2>${casinoLabel(ui,c.reward)}</h2><p>${ui.l(rewardOutcome(ui.g.save,c).description)}</p><p>${ui.tr('При выигрыше (50%): ','Win (50%): ')}<b>${ui.l(rewardOutcome(ui.g.save,c,true).description)}</b><br>${ui.tr('При проигрыше (50%): бонус потерян.','Loss (50%): bonus lost.')}</p>`:done?`<h2>${c.status==='skipped'?ui.tr('До следующего забега!','See you next run!'):c.factor===0?ui.tr('Бонус потерян. ДНК забега сохранена.','Bonus lost. Run DNA is safe.'):c.description?ui.l(c.description):c.addedDNA?`+${c.addedDNA} 🧬`:casinoLabel(ui,c.reward)}</h2>`:`<p>${ui.tr('Один бесплатный бонус. Вращение можно пропустить.','One free bonus. You can skip the spin.')}</p>`}</div><div id="casino-actions">${ready?ui.button('SPIN ↗','casinoSpin','','primary wide')+ui.button(ui.tr('Пропустить','Skip'),'casinoSkip','','wide subtle'):pending?ui.button(ui.tr('ЗАБРАТЬ БОНУС','KEEP BONUS'),'casinoKeep','','primary wide')+ui.button('DOUBLE OR BRAINROT · 50/50','casinoRisk','','wide')+`<small>${ui.tr('Одна попытка. ДНК за забег и покупки не участвуют.','One attempt. Run DNA and purchases are never at risk.')}</small>`:ui.button(ui.tr('В меню','Main menu'),'menu','','primary wide')+ui.button(ui.tr('Ещё забег','Play again'),'play','','wide')}</div><details class="wheel-odds"><summary>${ui.tr('Шансы наград','Reward odds')}</summary>${sectorsFor(c).map(s=>`<div><span>${casinoLabel(ui,s.id)}</span><b>${Math.round(s.angle/(2*Math.PI)*100)}%</b></div>`).join('')}</details><small class="casino-note">${ui.tr('Для нового обычного забега. Лимиты: 2 сундука, 3 перевыбора, 2 босса; сверх лимита — ДНК.','For a new Normal run. Caps: 2 chests, 3 rerolls, 2 bosses; overflow becomes DNA.')}</small></section>`;
 const canvas=ui.root.querySelector('#casino-wheel');drawWheel(ui,canvas,pool,c.status==='ready'?null:c.index);if(c.index!==null)canvas.style.transform=`rotate(${finalRotation(c)}deg)`;
}
function drawWheel(ui,canvas,pool,selected){const c=canvas.getContext('2d'),sectors=sectorsFor(ui.g.save.casino),colors=['#466744','#365345','#65513b','#3c5658'];c.clearRect(0,0,600,600);
 for(const sector of sectors){const {id,index,start,angle,center}=sector,a=-Math.PI/2+start,jackpot=id==='triple';c.beginPath();c.moveTo(300,300);c.arc(300,300,286,a,a+angle);c.closePath();c.fillStyle=jackpot?'#eccc63':index===selected?'#a5ca67':colors[index%colors.length];c.fill();c.strokeStyle=jackpot?'#ffe59b':'#d5e5af66';c.lineWidth=jackpot?1:2;c.stroke();
 c.save();c.translate(300,300);c.rotate(-Math.PI/2+center);c.textAlign='right';c.fillStyle=jackpot||index===selected?'#14261e':'#f1ecd4';c.font=`bold ${angle<.15?13:angle<.35?15:17}px system-ui`;const label=jackpot?'★':casinoLabel(ui,id).replace(' ДНК забега',' DNA').replace(' run DNA',' DNA');c.fillText(label,266,angle<.15?3:5,178);c.restore();}
 c.beginPath();c.arc(300,300,289,0,Math.PI*2);c.lineWidth=9;c.strokeStyle='#c7d69d';c.stroke();

}
export function casinoAction(ui,action){const save=ui.g.save,c=save.casino;if(!c)return;
 if(action==='casinoSpin'){if(!spinCasino(save))return;ui.store.write();const canvas=ui.root.querySelector('#casino-wheel');if(!canvas){renderCasino(ui);return;}ui.casinoAnimating=true;const actions=ui.root.querySelector('#casino-actions');actions.innerHTML='<p>'+ui.tr('Колесо выбирает бонус…','Finding your bonus…')+'</p>';ui.g.sound('spin');const pool=poolFor(c),target=finalRotation(c,5),begin=performance.now();let tick=-1;
 const frame=now=>{if(!canvas.isConnected){ui.casinoAnimating=false;return;}const t=Math.min(1,(now-begin)/2800),angle=target*(1-Math.pow(1-t,4));canvas.style.transform=`rotate(${angle}deg)`;const sector=sectorAtRotation(c,angle).index;if(sector!==tick){ui.g.sound('tick');tick=sector;}if(t<1)requestAnimationFrame(frame);else{ui.casinoAnimating=false;ui.g.sound(c.reward==='triple'?'jackpot':'reward');renderCasino(ui);}};requestAnimationFrame(frame);return;}
 if(ui.casinoAnimating)return;
 let result=false;if(action==='casinoSkip')result=skipCasino(save);if(action==='casinoKeep'||action==='casinoRisk')result=settleCasino(save,action==='casinoRisk');if(result){ui.store.write();if(action==='casinoRisk')ui.g.sound(c.factor?'doubleWin':'doubleLose');renderCasino(ui);}
}
