import {poolFor,rewardDefinitions,spinCasino,settleCasino,skipCasino,rewardValue} from '../systems/CasinoSystem.js';
export function casinoLabel(ui,id){return ui.l(rewardDefinitions[id]||[id,id]);}
function rewardDetail(ui,c){const n=rewardValue(c);if(n)return ui.tr(`Ещё +${n} ДНК к уже сохранённой награде.`,`An extra +${n} DNA on top of your saved reward.`);const info={startingChest:['Сундук рядом с героем в начале нового обычного забега.','A chest beside your hero at the start of the next Normal run.'],luckyStart:['+25% удачи на первые 3 минуты нового обычного забега.','+25% luck for the first 3 minutes of the next Normal run.'],extraRerolls:['Один перевыбор трёх карточек при повышении уровня.','Reroll all three level-up choices once.'],bossLoot:['Дополнительный сундук за первого босса нового обычного забега.','An extra chest from the first boss of the next Normal run.'],early67:['Первый 67 на 17-й базовой атаке, даже без улучшения. Затем обычный цикл, если 67 открыт.','First 67 on basic attack 17, even without the upgrade. Normal cycle follows if 67 is unlocked.']};return ui.l(info[c.reward]||['','']);}
export function renderCasino(ui){const c=ui.g.save.casino;if(!c){ui.show('MENU');return;}const pool=poolFor(c),pending=c.status==='pending',ready=c.status==='ready',done=!pending&&!ready;
 ui.root.innerHTML=`<section class="dialog casino"><span class="eyebrow">${c.victory?'WAVE 15 · VICTORY WHEEL':'ONE RUN · ONE FREE SPIN'}</span><h1>${c.victory?'VICTORY<br>WHEEL':'BRAINROT<br>CASINO'}</h1><p>${ui.store.available?ui.tr('ДНК за забег уже сохранена','Run DNA is already saved'):ui.tr('ДНК начислена на эту сессию','Run DNA credited for this session')}: <b>+${c.baseDNA}</b> 🧬</p><div class="wheel-wrap"><div class="wheel-pointer">▼</div><canvas id="casino-wheel" width="600" height="600" role="img" aria-label="${ui.tr('Колесо бонусов','Bonus wheel')}"></canvas><div class="wheel-hub">${c.victory?'★':'BR'}</div></div><div id="casino-outcome" role="status" aria-live="polite">${pending?`<h2>${casinoLabel(ui,c.reward)}</h2><p>${rewardDetail(ui,c)}</p><p>${ui.tr('Забрать или один раз рискнуть только этим бонусом?','Keep it or risk only this bonus once?')}</p>`:done?`<h2>${c.status==='skipped'?ui.tr('До следующего забега!','See you next run!'):c.factor===0?ui.tr('Бонус потерян. ДНК забега сохранена.','Bonus lost. Run DNA is safe.'):c.addedDNA?`+${c.addedDNA} 🧬`:casinoLabel(ui,c.reward)+' · '+ui.tr('сохранено: ','saved: ')+(c.savedBonus||1)}</h2>`:`<p>${ui.tr('Один бесплатный бонус. Вращение можно пропустить.','One free bonus. You can skip the spin.')}</p>`}</div><div id="casino-actions">${ready?ui.button('SPIN ↗','casinoSpin','','primary wide')+ui.button(ui.tr('Пропустить','Skip'),'casinoSkip','','wide subtle'):pending?ui.button(ui.tr('ЗАБРАТЬ БОНУС','KEEP BONUS'),'casinoKeep','','primary wide')+ui.button('DOUBLE OR BRAINROT · 50/50','casinoRisk','','wide')+`<small>${ui.tr('Один шанс: ×2 бонус или 0. ДНК за забег и покупки не участвуют.','One chance: ×2 bonus or 0. Run DNA and purchases are never at risk.')}</small>`:ui.button(ui.tr('В меню','Main menu'),'menu','','primary wide')+ui.button(ui.tr('Ещё забег','Play again'),'play','','wide')}</div><small class="casino-note">${ui.tr('Бонусы старта — для нового обычного забега. Сундуки: до 2; перевыборы: до 3; остальные: по 1.','Start bonuses apply to a new Normal run. Chests: up to 2; rerolls: up to 3; others: 1 each.')}</small></section>`;
 const canvas=ui.root.querySelector('#casino-wheel');drawWheel(ui,canvas,pool,c.status==='ready'?null:c.index);if(c.index!==null)canvas.style.transform=`rotate(${-((c.index+.5)*360/pool.length)}deg)`;
}
function drawWheel(ui,canvas,pool,selected){const c=canvas.getContext('2d'),n=pool.length,step=Math.PI*2/n,colors=['#466744','#365345','#65513b','#3c5658'];c.clearRect(0,0,600,600);for(let i=0;i<n;i++){const a=-Math.PI/2+i*step;c.beginPath();c.moveTo(300,300);c.arc(300,300,286,a,a+step);c.closePath();c.fillStyle=i===selected?'#a5ca67':colors[i%colors.length];c.fill();c.strokeStyle='#d5e5af66';c.lineWidth=2;c.stroke();c.save();c.translate(300,300);c.rotate(a+step/2);c.textAlign='right';c.fillStyle=i===selected?'#14261e':'#f1ecd4';c.font='bold 17px system-ui';const label=casinoLabel(ui,pool[i][0]).replace(' ДНК забега',' DNA').replace(' run DNA',' DNA');c.fillText(label,266,5,178);c.restore();}c.beginPath();c.arc(300,300,289,0,Math.PI*2);c.lineWidth=9;c.strokeStyle='#c7d69d';c.stroke();}
export function casinoAction(ui,action){const save=ui.g.save,c=save.casino;if(!c)return;
 if(action==='casinoSpin'){if(!spinCasino(save))return;ui.store.write();const canvas=ui.root.querySelector('#casino-wheel');if(!canvas){renderCasino(ui);return;}ui.casinoAnimating=true;const actions=ui.root.querySelector('#casino-actions');actions.innerHTML='<p>'+ui.tr('Колесо выбирает бонус…','Finding your bonus…')+'</p>';ui.g.sound('spin');const pool=poolFor(c),target=1800-(c.index+.5)*360/pool.length,begin=performance.now();let tick=-1;
 const frame=now=>{if(!canvas.isConnected){ui.casinoAnimating=false;return;}const t=Math.min(1,(now-begin)/2800),angle=target*(1-Math.pow(1-t,4));canvas.style.transform=`rotate(${angle}deg)`;const sector=Math.floor(angle/(360/pool.length));if(sector!==tick){ui.g.sound('tick');tick=sector;}if(t<1)requestAnimationFrame(frame);else{ui.casinoAnimating=false;ui.g.sound(c.reward==='triple'?'jackpot':'reward');renderCasino(ui);}};requestAnimationFrame(frame);return;}
 if(ui.casinoAnimating)return;
 let result=false;if(action==='casinoSkip')result=skipCasino(save);if(action==='casinoKeep'||action==='casinoRisk')result=settleCasino(save,action==='casinoRisk');if(result){ui.store.write();if(action==='casinoRisk')ui.g.sound(c.factor?'doubleWin':'doubleLose');renderCasino(ui);}
}
